name: Automated Data Preprocessing

on:
  push:
    branches: [ main ]
    paths:
      - 'balita_stunting_status/**'
      - 'preprocessing/**'
  workflow_dispatch:  # Allows manual triggering

jobs:
  preprocess:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run preprocessing
      run: |
        python preprocessing/automate_agum-medisa.py
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add preprocessing/data_balita_preprocessing/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update preprocessed data [skip ci]" && git push) 